In [5]:
import pandas as pd
import numpy as np

.isnull() 方法能夠輸出一個布林陣列將遺漏值標記為 True ，非遺漏值記錄為 False ；而  

.notnull() 則是輸出與前者恰恰相反的布林陣列

In [7]:
ser = pd.Series([5, None, 6, np.NaN])
print(ser.isnull())
print("\n")
print(ser.notnull())

0    False
1     True
2    False
3     True
dtype: bool


0     True
1    False
2     True
3    False
dtype: bool

In [8]:
df = pd.DataFrame([
    [1,      np.nan, 7.],
    [2,      5,      8.],
    [np.nan, 6,      9.]
])
df

     0    1    2
0  1.0  NaN  7.0
1  2.0  5.0  8.0
2  NaN  6.0  9.0

In [15]:
df = df.dropna()
df

     0    1    2
1  2.0  5.0  8.0

In [17]:
df = pd.DataFrame([
    [1,      np.nan, 7.],
    [2,      5,      8.],
    [np.nan, 6,      9.]
])

In [19]:
df = df.dropna(axis=1) #na就刪除欄位
df

     2
0  7.0
1  8.0
2  9.0

In [22]:
#面對遺漏值我們會選擇填補而非捨棄，Pandas 提供了.fillna() 方法，輸出以指定值替代 NaN 的資料

df = pd.DataFrame([
    [1,      np.nan, 7.],
    [2,      5,      8.],
    [np.nan, 6,      9.]
])

df = df.fillna(5566)
df

        0       1    2
0     1.0  5566.0  7.0
1     2.0     5.0  8.0
2  5566.0     6.0  9.0

# **除了以指定值填補遺漏值以外，亦可使用參數 method='ffill' 規則為碰到遺漏值時用前一筆資料填補，同理參數 method='bfill' 規則恰好相反，碰到遺漏值時用後一筆資料填補**

In [24]:
df = pd.DataFrame([
    [1,      np.nan, 7.],
    [2,      5,      8.],
    [np.nan, 6,      9.]
])

print(df.fillna(method='ffill'))
print('*'*50)
print(df.bfill())

#但是如果沒有前一筆或後一筆還是會nan
#用fillna的method或者直接寫df.ffill or df.bfill都可以

     0    1    2
0  1.0  NaN  7.0
1  2.0  5.0  8.0
2  2.0  6.0  9.0
**************************************************
     0    1    2
0  1.0  5.0  7.0
1  2.0  5.0  8.0
2  NaN  6.0  9.0